development:
  adapter: postgresql
  encoding: utf8
  database: iface_development
  pool: 5
  username: iface
  password: iface@123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: iface_test
  pool: 5
  username: iface
  password: iface@123

production:
  adapter: postgresql
  encoding: utf8
  database: iface_production
  pool: 5
  username: iface
  password: iface@123
